# Generated by Django 5.0.14 on 2026-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='source_kind',
            field=models.CharField(choices=[('wazuh_event', 'Wazuh Event'), ('vulnerability', 'Vulnerability'), ('agent_finding', 'Agent Finding'), ('api', 'API'), ('inbound_email', 'Inbound Email')], max_length=20),
        ),
    ]
