# Generated by Django 5.2.14 on 2026-05-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_add_inbound_email_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='pap',
            field=models.CharField(blank=True, choices=[('white', 'PAP:WHITE'), ('green', 'PAP:GREEN'), ('amber', 'PAP:AMBER'), ('red', 'PAP:RED')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='tlp',
            field=models.CharField(blank=True, choices=[('white', 'TLP:WHITE'), ('green', 'TLP:GREEN'), ('amber', 'TLP:AMBER'), ('red', 'TLP:RED')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source_kind',
            field=models.CharField(choices=[('wazuh_event', 'Wazuh Event'), ('vulnerability', 'Vulnerability'), ('agent_finding', 'Agent Finding'), ('api', 'API'), ('inbound_email', 'Inbound Email'), ('workflow', 'Workflow'), ('external', 'External')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
