# Generated by Django 5.2.14 on 2026-06-04 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_add_pap_tlp_description_nullable_severity'),
        ('security', '0011_organization_alert_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='alerts.alert')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_entities', to='security.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'entity_type', 'value', 'created_at'], name='alertentity_org_type_value_ts')],
            },
        ),
    ]
