# Generated by Django 5.0.14 on 2026-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_add_scheduled_search_source_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='source_kind',
            field=models.CharField(choices=[('wazuh_event', 'Wazuh Event'), ('vulnerability', 'Vulnerability'), ('agent_finding', 'Agent Finding'), ('api', 'API'), ('inbound_email', 'Inbound Email'), ('workflow', 'Workflow'), ('external', 'External'), ('scheduled_search', 'Scheduled Search Rule'), ('threat_hunt', 'Threat Hunt')], max_length=20),
        ),
    ]
