# Generated by Django 5.2.15 on 2026-06-19 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alter_alert_source_kind'),
        ('incidents', '0034_add_list_indexes'),
        ('security', '0016_organization_triage_work_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['state', 'created_at'], name='alert_state_ts'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'created_at'], name='alert_severity_ts'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'created_at'], name='alert_org_ts'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'state', 'created_at'], name='alert_org_state_ts'),
        ),
    ]
