# Generated by Django 5.2.16 on 2026-07-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_add_list_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='source_kind',
            field=models.CharField(choices=[('wazuh_event', 'Wazuh Event'), ('vulnerability', 'Vulnerability'), ('agent_finding', 'Agent Finding'), ('api', 'API'), ('inbound_email', 'Inbound Email'), ('workflow', 'Workflow'), ('external', 'External'), ('scheduled_search', 'Scheduled Search Rule'), ('threat_hunt', 'Threat Hunt'), ('webhook', 'Webhook')], max_length=20),
        ),
    ]
