# Generated by Django 5.0.14 on 2026-05-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='incident_var_mappings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='default_vars',
            field=models.TextField(blank=True, null=True),
        ),
    ]
