# Generated by Django 5.2.15 on 2026-06-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_wazuhactiveresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='wazuhactiveresponse',
            name='autonomous_triage_approved',
            field=models.BooleanField(default=False),
        ),
    ]
