# Generated by Django 5.2.14 on 2026-05-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_564b1f_idx',
            old_name='notif_recipient_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_0829fd_idx',
            old_name='notif_recipient_incident_email_idx',
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_system_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='inapp_system_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('delegation', 'Delegation'), ('comment', 'Comment'), ('state_change', 'State Change'), ('incident_alert', 'Incident Alert'), ('system_alert', 'System Alert')], max_length=30),
        ),
    ]
