# Generated by Django 5.0.14 on 2026-05-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_shown_inapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('notification_digest', 'Notification Digest'), ('incident_digest', 'Incident Digest'), ('invite', 'Account Invitation'), ('rejection', 'Signup Rejection'), ('signup_request', 'New Signup Request (Admin)'), ('test', 'Test Email')], max_length=60, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
