# Generated by Django 5.0.14 on 2026-05-17 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_emailtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferences',
            name='push_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='push_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='push_delegation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='push_incident_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='push_state_change',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
