# Generated by Django 5.0.14 on 2026-05-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_push_subscription_and_push_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_task_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='inapp_task_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='push_task_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('delegation', 'Delegation'), ('comment', 'Comment'), ('state_change', 'State Change'), ('incident_alert', 'Incident Alert'), ('system_alert', 'System Alert'), ('task_complete', 'Task Complete')], max_length=30),
        ),
    ]
