# Generated by Django 5.2.14 on 2026-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_add_task_complete_notification_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_shift_swap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='inapp_shift_swap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='push_shift_swap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('delegation', 'Delegation'), ('comment', 'Comment'), ('state_change', 'State Change'), ('incident_alert', 'Incident Alert'), ('system_alert', 'System Alert'), ('task_complete', 'Task Complete'), ('shift_swap', 'Shift Swap')], max_length=30),
        ),
    ]
