# Generated by Django 5.2.15 on 2026-06-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notificationpreferences_email_shift_swap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_hunt_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='inapp_hunt_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='push_hunt_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('delegation', 'Delegation'), ('comment', 'Comment'), ('state_change', 'State Change'), ('incident_alert', 'Incident Alert'), ('system_alert', 'System Alert'), ('task_complete', 'Task Complete'), ('hunt_complete', 'Hunt Complete'), ('shift_swap', 'Shift Swap')], max_length=30),
        ),
    ]
