services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: vels_online
      POSTGRES_USER: vels
      POSTGRES_PASSWORD: vels_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vels -d vels_online"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    platform: linux/amd64
    build: ./backend
    image: registry.vels.online/vels/backend:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: dev-secret-key-not-for-production
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1,backend"
      DATABASE_URL: postgres://vels:vels_password@db:5432/vels_online
    depends_on:
      db:
        condition: service_healthy

  frontend:
    platform: linux/amd64
    image: registry.vels.online/vels/frontend:latest
    build:
      context: ./frontend
      #dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

volumes:
  postgres_data:
