# Generated by Django 5.2.13 on 2026-05-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorvisibility',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
