# Generated by Django 5.0.14 on 2026-05-22 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_incidentcontact'),
        ('incidents', '0017_asset_is_active_last_seen_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentcontact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='incidentcontact',
            name='role',
        ),
        migrations.RemoveField(
            model_name='incidentcontact',
            name='sent_at',
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('role', models.CharField(blank=True, choices=[('notified', 'Notified'), ('questioned', 'Questioned')], max_length=20)),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='contacts.contact')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='incidents.incident')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='contacts.contactmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
