# Generated by Django 5.2.15 on 2026-07-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contactmessage_incidentcontact_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentcontact',
            name='notify_level',
            field=models.CharField(choices=[('closure_only', 'Closure only'), ('all_updates', 'All updates')], default='closure_only', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='role',
            field=models.CharField(blank=True, choices=[('notified', 'Notified'), ('questioned', 'Questioned'), ('update', 'Update')], max_length=20),
        ),
    ]
