# Generated by Django 5.0.14 on 2026-06-12 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0030_alter_incident_source_kind'),
        ('security', '0013_organization_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('seed_kind', models.CharField(choices=[('question', 'Question'), ('url', 'Report URL')], default='question', max_length=16)),
                ('seed_text', models.TextField(blank=True, default='')),
                ('seed_url', models.URLField(blank=True, default='', max_length=2000)),
                ('scope_all_orgs', models.BooleanField(default=True)),
                ('lookback_days', models.PositiveIntegerField(default=30)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='created', max_length=16)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunts', to=settings.AUTH_USER_MODEL)),
                ('scope_orgs', models.ManyToManyField(blank=True, related_name='hunts', to='security.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HuntEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('turn', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(max_length=16)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hunts.hunt')),
            ],
            options={
                'ordering': ['seq'],
                'unique_together': {('hunt', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='HuntFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens', models.CharField(blank=True, default='', max_length=64)),
                ('source_index', models.CharField(blank=True, default='', max_length=255)),
                ('wazuh_doc_id', models.CharField(blank=True, default='', max_length=255)),
                ('raw_doc', models.JSONField(blank=True, default=dict)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='hunts.hunt')),
                ('materialised_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_findings', to='incidents.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_findings', to='security.organization')),
            ],
            options={
                'ordering': ['organization_id', 'created_at'],
                'unique_together': {('hunt', 'source_index', 'wazuh_doc_id')},
            },
        ),
    ]
