# Generated by Django 5.0.14 on 2026-06-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('scoping', 'Scoping'), ('scoping_running', 'Scoping (running)'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='created', max_length=16),
        ),
    ]
