---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-velsonline
spec:
  instances: 2
  storage:
    storageClass: nfs-csi
    size: 10Gi

  managed:
    roles:
      - name: velsonline
        superuser: true
        login: true

  bootstrap:
    recovery:
      source: cluster-velsonline
      database: velsonline
      owner: velsonline

  externalClusters:
    - name: cluster-velsonline
      barmanObjectStore:
        destinationPath: s3://vels-cnpg-backups/
        endpointURL: https://s3.eu-central-1.wasabisys.com
        s3Credentials:
          accessKeyId:
            name: minio
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: minio
            key: ACCESS_SECRET_KEY
        wal:
          maxParallel: 8
#  bootstrap:
#    initdb:
#      database: velsonline
#      owner: velsonline


  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-store

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-velsonline
  labels:
    prometheus: "true"
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: cluster-velsonline
  podMetricsEndpoints:
  - port: metrics
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-store
spec:
  retentionPolicy: "14d"
  configuration:
    destinationPath: s3://vels-cnpg-backups/
    endpointURL: https://s3.eu-central-1.wasabisys.com
    s3Credentials:
      accessKeyId:
        name: minio
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: minio
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-velsonline-db
spec:
  cluster:
    name: cluster-velsonline
  schedule: '0 9 0 * * *'
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  refreshInterval: "120s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: minio
    creationPolicy: Owner

  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: kv/velsonline
        property: ACCESS_KEY_ID

    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: kv/velsonline
        property: ACCESS_SECRET_KEY
