apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: migrate
          image: registry.vels.online/vels/backend:latest
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - secretRef:
                name: backend-secret

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cluster-velsonline-app
                  key: fqdn-uri
            - name: ALLOWED_HOSTS
              value: "vels.online"
            - name: DEBUG
              value: "False"
            - name: CSRF_TRUSTED_ORIGINS
              value: "https://vels.online"

      containers:
        - name: backend
          image: registry.vels.online/vels/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: backend-secret
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cluster-velsonline-app
                  key: fqdn-uri

            - name: ALLOWED_HOSTS
              value: "vels.online"
            - name: CSRF_TRUSTED_ORIGINS
              value: "https://vels.online"
            - name: DEBUG
              value: "True"

#          readinessProbe:
#            httpGet:
#              path: /api/health/
#              port: 8000
#            initialDelaySeconds: 5
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /api/health/
#              port: 8000
#            initialDelaySeconds: 15
#            periodSeconds: 20
