---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
spec:
  refreshInterval: "120s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backend-secret
    creationPolicy: Owner

  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: kv/velsonline
        property: SECRET_KEY

    - secretKey: AUTHENTIK_CLIENT_SECRET
      remoteRef:
        key: kv/velsonline
        property: AUTHENTIK_CLIENT_SECRET

    - secretKey: AUTHENTIK_SERVER_URL
      remoteRef:
        key: kv/velsonline
        property: AUTHENTIK_SERVER_URL

    - secretKey: AUTHENTIK_CLIENT_ID
      remoteRef:
        key: kv/velsonline
        property: AUTHENTIK_CLIENT_ID

    - secretKey: UPTIMEROBOT_API_KEY
      remoteRef:
        key: kv/velsonline
        property: UPTIMEROBOT_API_KEY
