---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
spec:
  refreshInterval: "120s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backend-secret
    creationPolicy: Owner

  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: kv/velsonline
        property: SECRET_KEY

    - secretKey: AUTHENTIK_CLIENT_SECRET
      remoteRef:
        key: kv/velsonline
        property: AUTHENTIK_CLIENT_SECRET

    - secretKey: AUTHENTIK_SERVER_URL
      remoteRef:
        key: kv/velsonline
        property: AUTHENTIK_SERVER_URL

    - secretKey: AUTHENTIK_CLIENT_ID
      remoteRef:
        key: kv/velsonline
        property: AUTHENTIK_CLIENT_ID

    - secretKey: UPTIMEROBOT_API_KEY
      remoteRef:
        key: kv/velsonline
        property: UPTIMEROBOT_API_KEY

    - secretKey: REDIS_URL
      remoteRef:
        key: kv/velsonline
        property: REDIS_URL

    - secretKey: WASABI_ENDPOINT
      remoteRef:
        key: kv/velsonline
        property: WASABI_ENDPOINT

    - secretKey: WASABI_BUCKET
      remoteRef:
        key: kv/velsonline
        property: WASABI_BUCKET

    - secretKey: WASABI_ACCESS_KEY
      remoteRef:
        key: kv/velsonline
        property: WASABI_ACCESS_KEY

    - secretKey: WASABI_SECRET_KEY
      remoteRef:
        key: kv/velsonline
        property: WASABI_SECRET_KEY

    - secretKey: WAZUH_API_URL
      remoteRef:
        key: kv/velsonline
        property: WAZUH_API_URL

    - secretKey: WAZUH_API_USER
      remoteRef:
        key: kv/velsonline
        property: WAZUH_API_USER

    - secretKey: WAZUH_API_PASSWORD
      remoteRef:
        key: kv/velsonline
        property: WAZUH_API_PASSWORD

    - secretKey: WAZUH_MANAGER_HOST
      remoteRef:
        key: kv/velsonline
        property: WAZUH_MANAGER_HOST

    - secretKey: WAZUH_INDEXER_URL
      remoteRef:
        key: kv/velsonline
        property: WAZUH_INDEXER_URL

    - secretKey: WAZUH_INDEXER_USER
      remoteRef:
        key: kv/velsonline
        property: WAZUH_INDEXER_USER

    - secretKey: WAZUH_INDEXER_PASSWORD
      remoteRef:
        key: kv/velsonline
        property: WAZUH_INDEXER_PASSWORD

    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: kv/velsonline
        property: GITHUB_TOKEN

    - secretKey: GITHUB_REPO
      remoteRef:
        key: kv/velsonline
        property: GITHUB_REPO

    - secretKey: EMAIL_HOST
      remoteRef:
        key: kv/velsonline
        property: EMAIL_HOST

    - secretKey: EMAIL_HOST_USER
      remoteRef:
        key: kv/velsonline
        property: EMAIL_HOST_USER

    - secretKey: EMAIL_HOST_PASSWORD
      remoteRef:
        key: kv/velsonline
        property: EMAIL_HOST_PASSWORD

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: valkey-secret
spec:
  refreshInterval: "120s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: valkey-secret
    creationPolicy: Owner
  data:
    - secretKey: valkey-password
      remoteRef:
        key: kv/velsonline
        property: VALKEY_PASSWORD

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-class-acr
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  secretObjects:
    - data:
        - key: .dockerconfigjson
          objectName: .dockerconfigjson
      secretName: azure-acr
      type: kubernetes.io/dockerconfigjson
  parameters:
    vaultAddress: {{ .Values.vaultAddress }}
    vaultKubernetesMountPath: "kubernetes/{{ .Values.clusterName }}"
    roleName: "azure_devops_agent_acr"
    objects: |
      - objectName: ".dockerconfigjson"
        secretPath: "secret/devops/agents/acr"
        secretKey: ".dockerconfigjson"
