---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: mobile
#spec:
#  replicas: 1
#  revisionHistoryLimit: 2
#  selector:
#    matchLabels:
#      app: mobile
#  template:
#    metadata:
#      labels:
#        app: mobile
#    spec:
#      imagePullSecrets:
#        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
#      containers:
#        - name: mobile
#          image: {{ .Values.mobile.image.repository }}:{{ .Values.mobile.image.tag }}
#          imagePullPolicy: Always
#          ports:
#            - containerPort: 80
#          readinessProbe:
#            httpGet:
#              path: /metadata.json
#              port: 80
#            initialDelaySeconds: 5
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /metadata.json
#              port: 80
#            initialDelaySeconds: 10
#            periodSeconds: 20
