apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: celery-worker
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: Always
          command: ["celery", "-A", "config", "worker", "-l", "INFO"]
          resources:
            requests:
              memory: "1024Mi"
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cluster-velsonline-app
                  key: fqdn-uri
            - name: ALLOWED_HOSTS
              value: "vels.online"
            - name: CSRF_TRUSTED_ORIGINS
              value: "https://vels.online"
            - name: DEBUG
              value: "False"
