# Generated by Django 5.0.14 on 2026-05-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
        ('incidents', '0011_incident_needs_tuning'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='automation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='automations.automation'),
        ),
        migrations.AddField(
            model_name='task',
            name='automation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='semaphore_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='tasktemplateitem',
            name='automation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='automations.automation'),
        ),
    ]
