# Generated by Django 5.0.14 on 2026-05-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_asset_incidentasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL')], max_length=10)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iocs', to='incidents.incident')),
            ],
            options={
                'ordering': ['kind', 'value'],
                'unique_together': {('incident', 'kind', 'value')},
            },
        ),
    ]
