# Generated by Django 5.0.14 on 2026-05-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0015_add_ioc_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='kind',
            field=models.CharField(choices=[('user', 'User'), ('ai_triage', 'AI Triage'), ('system', 'System')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
