# Generated by Django 5.0.14 on 2026-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0016_comment_kind_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
