# Generated by Django 5.0.14 on 2026-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0020_ioc_enrichment_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='source_kind',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('wazuh_event', 'Wazuh Event'), ('vulnerability', 'Vulnerability'), ('agent_finding', 'Agent Finding'), ('inbound_email', 'Inbound Email')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='kind',
            field=models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('email', 'Email Address')], max_length=10),
        ),
    ]
