# Generated by Django 5.2.14 on 2026-05-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0021_add_inbound_email_source_and_kind_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='source_kind',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('wazuh_event', 'Wazuh Event'), ('vulnerability', 'Vulnerability'), ('agent_finding', 'Agent Finding'), ('inbound_email', 'Inbound Email'), ('workflow', 'Workflow'), ('external', 'External')], default='manual', max_length=20),
        ),
    ]
