# Generated by Django 5.2.14 on 2026-05-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0022_add_workflow_external_source_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
    ]
