# Generated by Django 5.0.14 on 2026-06-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0028_add_asset_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
