# Generated by Django 5.0.14 on 2026-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0029_incident_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='source_kind',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('wazuh_event', 'Wazuh Event'), ('vulnerability', 'Vulnerability'), ('agent_finding', 'Agent Finding'), ('inbound_email', 'Inbound Email'), ('workflow', 'Workflow'), ('external', 'External'), ('correlation', 'Correlation Rule'), ('scheduled_search', 'Scheduled Search Rule'), ('threat_hunt', 'Threat Hunt')], default='manual', max_length=20),
        ),
    ]
