# Generated by Django 5.2.15 on 2026-06-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0030_alter_incident_source_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('needs_tuning', 'Needs Tuning'), ('pending_closure', 'Pending Closure'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
