# Generated by Django 5.2.15 on 2026-06-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0031_alter_incident_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='triage_worked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
