# Generated by Django 5.2.15 on 2026-06-18 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0032_incident_triage_worked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], max_length=3)),
                ('port', models.PositiveIntegerField()),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nat_exposures', to='incidents.asset')),
            ],
            options={
                'ordering': ['protocol', 'port'],
            },
        ),
    ]
