# Generated by Django 5.2.15 on 2026-06-19 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_wazuhactiveresponse_autonomous_triage_approved'),
        ('incidents', '0033_natexposure'),
        ('ingress', '0004_route_backend_asset'),
        ('security', '0016_organization_triage_work_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'is_active'], name='asset_org_active'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['state', 'created_at'], name='incident_state_ts'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity', 'created_at'], name='incident_severity_ts'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'created_at'], name='incident_org_ts'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'state', 'created_at'], name='incident_org_state_ts'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['state', 'created_at'], name='task_state_ts'),
        ),
    ]
