# Generated by Django 5.2.15 on 2026-06-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0034_add_list_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('no_impact', 'No Impact'), ('duplicate', 'Duplicate'), ('informational', 'Informational'), ('accepted_risk', 'Accepted Risk')], max_length=20, null=True),
        ),
    ]
