# Generated by Django 5.2.15 on 2026-06-25 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0035_alter_incident_closure_reason'),
        ('security', '0018_organization_ioc_exclusions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audience', models.CharField(choices=[('customer', 'Customer'), ('internal', 'Internal')], default='customer', max_length=20)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('intro_text', models.TextField(blank=True, default='')),
                ('outro_text', models.TextField(blank=True, default='')),
                ('recommendations_text', models.TextField(blank=True, default='')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='security.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=32, unique=True)),
                ('template_name', models.CharField(max_length=255)),
                ('audience', models.CharField(choices=[('customer', 'Customer'), ('internal', 'Internal')], max_length=20)),
                ('tlp', models.CharField(max_length=10)),
                ('incident_state', models.CharField(max_length=20)),
                ('executive_summary', models.TextField(blank=True, default='')),
                ('content', models.JSONField(blank=True, default=dict)),
                ('s3_key', models.CharField(max_length=500, unique=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='incidents.incident')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='incidents.reporttemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['incident', 'generated_at'], name='incidents_r_inciden_5afeaf_idx')],
            },
        ),
    ]
