# Generated by Django 5.2.15 on 2026-07-06 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0036_reporttemplate_report'),
        ('security', '0018_organization_ioc_exclusions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_severity', models.CharField(blank=True, default='', max_length=10)),
                ('human_severity', models.CharField(blank=True, default='', max_length=10)),
                ('agent_disposition', models.CharField(blank=True, default='', max_length=32)),
                ('human_disposition', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_corrections', to=settings.AUTH_USER_MODEL)),
                ('agent_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incidents.subject')),
                ('human_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incidents.subject')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_corrections', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['incident', 'created_at'], name='correction_incident_ts')],
            },
        ),
        migrations.CreateModel(
            name='TriageLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(blank=True, default='', max_length=20)),
                ('selector', models.TextField(blank=True, default='')),
                ('guidance', models.TextField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='proposed', max_length=12)),
                ('provenance', models.CharField(choices=[('distilled_from_human_close', 'Distilled from human close'), ('agent_proposed', 'Agent proposed'), ('staff_authored', 'Staff authored')], max_length=32)),
                ('applied_count', models.PositiveIntegerField(default=0)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('contradiction_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_triage_lessons', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_triage_lessons', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ManyToManyField(blank=True, related_name='justified_triage_lessons', to='incidents.incident')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triage_lessons', to='security.organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_lessons', to='incidents.subject')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['subject', 'status'], name='lesson_subject_status'), models.Index(fields=['organization', 'status'], name='lesson_org_status')],
            },
        ),
    ]
