# Generated by Django 5.2.15 on 2026-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0038_alter_incident_source_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='origin',
            field=models.CharField(choices=[('staff', 'Staff'), ('partner_inbound', 'Partner (inbound)'), ('ai', 'AI')], default='staff', max_length=20),
        ),
    ]
