# Generated by Django 5.2.15 on 2026-07-12 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0039_comment_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistillationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('eligible_count', models.IntegerField(default=0)),
                ('cluster_count', models.IntegerField(default=0)),
                ('proposed_count', models.IntegerField(default=0)),
                ('proposed_global_count', models.IntegerField(default=0)),
                ('clusters', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
