# Generated by Django 5.2.15 on 2026-07-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0040_distillationrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contact_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='contact_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tasktemplateitem',
            name='contact_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tasktemplateitem',
            name='contact_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tasktemplateitem',
            name='is_contact_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated'), ('wazuh_response', 'Wazuh Response'), ('contact', 'Contact')], default='manual', max_length=20),
        ),
    ]
