# Generated by Django 5.2.16 on 2026-07-23 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0008_alter_alert_source_kind'),
        ('incidents', '0042_alter_incident_source_kind'),
        ('security', '0021_organization_triage_fp_close_bar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_type', models.CharField(choices=[('incident', 'Incident'), ('alert', 'Alert'), ('asset', 'Asset')], max_length=20)),
                ('state', models.CharField(choices=[('capturing', 'Capturing'), ('active', 'Active'), ('paused', 'Paused')], default='capturing', max_length=20)),
                ('path_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('collection_root_path', models.CharField(blank=True, default='', max_length=500)),
                ('idempotency_key_path', models.CharField(blank=True, default='', max_length=500)),
                ('field_mappings', models.JSONField(blank=True, default=dict)),
                ('entity_mappings', models.JSONField(blank=True, default=dict)),
                ('identity_field', models.CharField(blank=True, default='name', max_length=64)),
                ('max_body_bytes', models.PositiveIntegerField(default=1000000)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=120)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_endpoints', to='security.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CapturedPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_payloads', to='webhook_ingest.ingestendpoint')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PayloadElementOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_index', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('outcome', models.CharField(choices=[('created', 'Created'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alerts.alert')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incidents.asset')),
                ('captured_payload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='webhook_ingest.capturedpayload')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='webhook_ingest.ingestendpoint')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incidents.incident')),
            ],
            options={
                'ordering': ['captured_payload', 'element_index'],
            },
        ),
        migrations.AddIndex(
            model_name='capturedpayload',
            index=models.Index(fields=['endpoint', 'status', 'received_at'], name='cap_ep_status_ts'),
        ),
        migrations.AddIndex(
            model_name='capturedpayload',
            index=models.Index(fields=['received_at'], name='cap_received_ts'),
        ),
        migrations.AddIndex(
            model_name='payloadelementoutcome',
            index=models.Index(fields=['endpoint', 'idempotency_key', 'outcome'], name='outcome_ep_idem_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payloadelementoutcome',
            unique_together={('captured_payload', 'element_index')},
        ),
    ]
