# Generated by Django 5.2.14 on 2026-05-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0006_organization_max_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('fqdn', models.CharField(max_length=255, unique=True)),
                ('backend_host', models.CharField(max_length=255)),
                ('backend_port', models.PositiveIntegerField()),
                ('backend_protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', max_length=5)),
                ('backend_type', models.CharField(choices=[('direct', 'Direct'), ('netbird', 'NetBird')], default='direct', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('error', 'Error')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='security.organization')),
            ],
        ),
    ]
