# Generated by Django 5.2.14 on 2026-05-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='dns_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
