# Generated by Django 5.2.15 on 2026-06-18 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0033_natexposure'),
        ('ingress', '0003_strip_backend_host_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='backend_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'host'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_exposures', to='incidents.asset'),
        ),
    ]
