from django.urls import path

from .views import (
    AgentEventDetailView,
    AgentEventsView,
    AgentListView,
    AgentVulnerabilitiesView,
    AgentVulnerabilityDetailView,
    CveDetailView,
    DashboardView,
    DownloadDeleteView,
    DownloadListView,
    DownloadPresignedView,
    DownloadUploadView,
    EnrollmentView,
    FleetEventsView,
    FleetVulnerabilitiesView,
    FleetVulnerabilityTrendView,
    OrganizationListView,
    SecurityRefreshView,
    WorkPackageItemPatchView,
    WorkPackageView,
)

urlpatterns = [
    path("organizations/", OrganizationListView.as_view()),
    path("agents/", AgentListView.as_view()),
    path("agents/<str:agent_id>/events/", AgentEventsView.as_view()),
    path("agents/<str:agent_id>/events/<str:event_id>/", AgentEventDetailView.as_view()),
    path("agents/<str:agent_id>/vulnerabilities/", AgentVulnerabilitiesView.as_view()),
    path("agents/<str:agent_id>/vulnerabilities/<str:vuln_id>/", AgentVulnerabilityDetailView.as_view()),
    path("dashboard/", DashboardView.as_view()),
    path("dashboard/refresh/", SecurityRefreshView.as_view()),
    path("events/", FleetEventsView.as_view()),
    path("vulnerabilities/", FleetVulnerabilitiesView.as_view()),
    path("vulnerabilities/trend/", FleetVulnerabilityTrendView.as_view()),
    path("vulnerabilities/<str:cve_id>/", CveDetailView.as_view()),
    path("enrollment/", EnrollmentView.as_view()),
    path("downloads/", DownloadListView.as_view()),
    path("downloads/<int:pk>/", DownloadDeleteView.as_view()),
    path("downloads/<int:pk>/presigned/", DownloadPresignedView.as_view()),
    path("downloads/<int:pk>/upload/", DownloadUploadView.as_view()),
    path("work-package/", WorkPackageView.as_view()),
    path("work-package/items/<int:item_id>/", WorkPackageItemPatchView.as_view()),
]
