backend:
  image:
    repository: registry.vels.online/vels/backend
    tag: 0.0.9
frontend:
  image:
    repository: registry.vels.online/vels/frontend
    tag: 0.0.9
imagePullSecrets:
  - name: registry-credentials
