# Generated by Django 5.2.13 on 2026-05-05 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_vulnerabilitysnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_work_packages', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_packages', to='security.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('cvss_score', models.FloatField()),
                ('description', models.TextField()),
                ('references', models.JSONField(default=list)),
                ('affected_agent_count', models.IntegerField()),
                ('impact_score', models.FloatField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('accepted_risk', 'Accepted Risk')], default='open', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('affected_agents', models.JSONField(default=list)),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='security.workpackage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workpackage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('org',), name='unique_active_work_package_per_org'),
        ),
    ]
