# Generated by Django 5.2.14 on 2026-05-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_riskacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_routes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
