# Generated by Django 5.0.14 on 2026-05-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_orginvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='triage_fp_threshold',
            field=models.FloatField(default=0.95),
        ),
    ]
