# Generated by Django 5.2.14 on 2026-06-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_organization_alert_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='llm_residual_autocreate_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
