# Generated by Django 5.0.14 on 2026-06-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_organization_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_infrastructure',
            field=models.BooleanField(default=False),
        ),
    ]
