# Generated by Django 5.2.15 on 2026-06-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_seed_infrastructure_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='triage_work_threshold',
            field=models.FloatField(default=0.95),
        ),
    ]
