# Generated by Django 5.2.15 on 2026-06-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_organization_triage_work_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
