# Generated by Django 5.2.15 on 2026-07-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0019_serviceaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='last_used_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
