# Generated by Django 5.2.15 on 2026-07-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0020_serviceaccount_allowed_ips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='triage_fp_close_bar',
            field=models.FloatField(default=0.8),
        ),
    ]
