# Generated by Django 5.2.14 on 2026-05-11 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0010_attachment'),
        ('security', '0005_riskacceptance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreedRuleId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(unique=True)),
                ('freed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rule_id'],
            },
        ),
        migrations.CreateModel(
            name='WazuhRuleIdPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_assigned_id', models.IntegerField(default=199999)),
            ],
            options={
                'verbose_name': 'Wazuh Rule ID Pool',
            },
        ),
        migrations.CreateModel(
            name='ExceptionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wazuh_rule_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('trigger_rule_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('match_value', models.CharField(blank=True, default='', max_length=512)),
                ('field_name', models.CharField(blank=True, default='', max_length=255)),
                ('field_value', models.CharField(blank=True, default='', max_length=512)),
                ('field_type', models.CharField(choices=[('pcre2', 'PCRE2'), ('literal', 'Literal')], default='literal', max_length=10)),
                ('scope', models.CharField(choices=[('org', 'Organisation'), ('global', 'Global')], default='org', max_length=10)),
                ('agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exception_rules', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_rules', to='incidents.incident')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_rules', to='security.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
