# Generated by Django 5.2.14 on 2026-06-02 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncall', '0002_shiftblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationTemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_slots', to=settings.AUTH_USER_MODEL)),
                ('shift_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_slots', to='oncall.shiftblock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('day_of_week', 'shift_block'), name='unique_dow_block')],
            },
        ),
    ]
