# Generated by Django 5.2.14 on 2026-06-02 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncall', '0003_rotationtemplateslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('kind', models.CharField(choices=[('swap', 'Swap'), ('cover_offer', 'Cover Offer')], default='swap', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_overrides', to=settings.AUTH_USER_MODEL)),
                ('original_analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_overrides', to=settings.AUTH_USER_MODEL)),
                ('override_analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_overrides', to=settings.AUTH_USER_MODEL)),
                ('shift_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='oncall.shiftblock')),
            ],
        ),
    ]
