# Generated by Django 5.2.15 on 2026-07-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeInboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, default='', max_length=320)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('drop_reason', models.CharField(blank=True, default='', max_length=100)),
                ('body_excerpt', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['received_at'], name='intake_received_idx')],
            },
        ),
    ]
