# Generated by Django 5.2.15 on 2026-07-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_intakeinboxmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeinboxmessage',
            name='raw_s3_key',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
