# Generated by Django 5.2.15 on 2026-07-17 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0040_distillationrun'),
        ('partners', '0003_intakeinboxmessage_raw_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeinboxmessage',
            name='replayed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakeinboxmessage',
            name='replayed_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incidents.incident'),
        ),
    ]
