#!/usr/bin/env python3
"""
Fetch all open GitHub issues labelled needs-triage and run Claude Code on each
one to perform automated triage: classify the issue, write an agent brief, post
it as a comment, and update the issue labels.
"""

import json
import subprocess
import sys
import textwrap

LABEL = "needs-triage"

# Injected into the claude -p call for every issue.
# {number} is replaced with the actual issue number.
PROMPT_TEMPLATE = textwrap.dedent("""\
    You are performing automated triage on GitHub issue #{number} in this repository.

    Every comment you post to the issue tracker MUST start with this disclaimer on its own line:
    > *This was generated by AI during triage.*

    Follow these steps in order:

    1. READ THE ISSUE
       Run: gh issue view {number} --comments
       Parse the full body, all comments, existing labels, and the reporter.

    2. EXPLORE THE CODEBASE
       Use grep, find, and file reads to understand the area of code the issue touches.
       Read CONTEXT.md and any relevant docs/adr/ files.
       Read .out-of-scope/*.md and check if any prior rejection matches this issue.

    3. CLASSIFY
       Assign exactly one category role (bug or enhancement) and determine the correct
       state role from: needs-info, ready-for-agent, ready-for-human, wontfix.

       Rules:
       - ready-for-agent  → issue is fully specified; an AFK agent can implement it
       - ready-for-human  → needs judgment calls, external access, or manual testing
       - needs-info       → reporter must answer questions before work can begin
       - wontfix (bug)    → not a real bug or out of scope
       - wontfix (enhancement) → feature is explicitly out of scope

    4. WRITE THE AGENT BRIEF (for ready-for-agent or ready-for-human)
       Use the template below. Follow these rules strictly:
       - Describe WHAT, not HOW
       - No file paths, no line numbers
       - Acceptance criteria must be independently testable
       - State explicit out-of-scope boundaries

       Template:
       ## Agent Brief

       **Category:** bug / enhancement
       **Summary:** one-line description

       **Current behavior:**
       <what happens now>

       **Desired behavior:**
       <what should happen after the work is done, including edge cases>

       **Key interfaces:**
       - `TypeName` — what needs to change and why

       **Acceptance criteria:**
       - [ ] criterion 1
       - [ ] criterion 2

       **Out of scope:**
       - thing that should NOT be touched

    5. ACT — perform ALL of the following:

       a. Post a comment on the issue with the triage outcome. If state is
          ready-for-agent or ready-for-human, include the full Agent Brief in
          the comment. If state is needs-info, post a needs-info comment using
          this structure:
            ## Triage Notes
            **What we've established so far:**
            - …
            **What we still need from you (@reporter):**
            - specific question 1

       b. Remove the needs-triage label:
          gh issue edit {number} --remove-label "needs-triage"

       c. Apply the new state label (use the exact string from this mapping):
          needs-info       → needs-info
          ready-for-agent  → ready-for-agent
          ready-for-human  → ready-for-human
          wontfix          → wontfix

       d. Apply the category label (bug or enhancement):
          gh issue edit {number} --add-label "<category>"

       e. If state is wontfix and category is enhancement:
          Write a .out-of-scope/<concept>.md file with:
            # <Concept Name>
            **Decision:** will not implement
            **Reason:** <one paragraph>
            **Prior requests:** #<number>
          Then close the issue:
            gh issue close {number} --comment "> *This was generated by AI during triage.*\n\nClosed as wontfix. See .out-of-scope/ for reasoning."

       f. If state is wontfix and category is bug:
          Close the issue with a polite explanation:
            gh issue close {number} --comment "> *This was generated by AI during triage.*\n\n<explanation>"

    Do not ask for confirmation. Complete all steps autonomously.
""")


def fetch_issues() -> list[dict]:
    result = subprocess.run(
        [
            "gh", "issue", "list",
            "--label", LABEL,
            "--state", "open",
            "--json", "number,title",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def run_claude(issue_number: int, issue_title: str) -> None:
    prompt = PROMPT_TEMPLATE.format(number=issue_number)
    print(f"\n{'='*60}")
    print(f"Triaging issue #{issue_number}: {issue_title}")
    print(f"{'='*60}")
    subprocess.run(
        ["claude", "-p", prompt],
        check=False,  # don't abort the loop if one issue fails
    )


def main() -> None:
    try:
        issues = fetch_issues()
    except subprocess.CalledProcessError as exc:
        print(f"Failed to fetch issues: {exc.stderr}", file=sys.stderr)
        sys.exit(1)

    if not issues:
        print(f"No open issues with label '{LABEL}' found.")
        return

    print(f"Found {len(issues)} issue(s) with label '{LABEL}'.")

    for issue in issues:
        run_claude(issue["number"], issue["title"])

    print("\nAll issues triaged.")


if __name__ == "__main__":
    main()
