# Generated by Django 5.2.14 on 2026-06-04 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_add_alert_entity'),
        ('correlations', '0001_initial'),
        ('incidents', '0026_add_correlation_source_kind'),
        ('security', '0012_add_llm_residual_autocreate_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField()),
                ('confidence', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_suggestion', to='incidents.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_suggestions', to='security.organization')),
                ('proposed_alerts', models.ManyToManyField(blank=True, related_name='detection_suggestions', to='alerts.alert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
