# Generated by Django 5.2.14 on 2026-06-06 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0004_add_search_rule_multi_leg'),
        ('security', '0012_add_llm_residual_autocreate_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_rules', to='security.organization'),
        ),
        migrations.CreateModel(
            name='SearchRuleMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_rule_mutes', to='security.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='correlations.searchrule')),
            ],
            options={
                'unique_together': {('organization', 'rule')},
            },
        ),
    ]
