# Generated by Django 5.0.14 on 2026-06-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0007_add_diversity_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRuleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('expect_fire', models.BooleanField(default=True)),
                ('samples', models.JSONField(default=list)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('never', 'Never run'), ('pass', 'Pass'), ('fail', 'Fail'), ('error', 'Error')], default='never', max_length=10)),
                ('last_diagnostics', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='correlations.searchrule')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
