# Generated by Django 5.0.14 on 2026-06-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0008_searchruletest'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrule',
            name='time_window_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='searchrule',
            name='time_window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchrule',
            name='time_window_mode',
            field=models.CharField(blank=True, choices=[('inside', 'Inside window'), ('outside', 'Outside window')], default='inside', max_length=10),
        ),
        migrations.AddField(
            model_name='searchrule',
            name='time_window_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
