# Generated by Django 5.2.15 on 2026-06-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0009_searchrule_time_window_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchruleleg',
            name='count_operator',
            field=models.CharField(choices=[('gte', 'At least (≥)'), ('lte', 'At most (≤)')], default='gte', max_length=3),
        ),
    ]
