# Generated by Django 5.2.15 on 2026-06-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0010_searchruleleg_count_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrule',
            name='baseline_lookback_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='searchruleleg',
            name='novelty_field',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
