# Generated by Django 5.2.15 on 2026-07-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlations', '0011_searchrule_baseline_lookback_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionsuggestion',
            name='detector',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detectionsuggestion',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
