from django.urls import path

from .views import (
    ApplyTemplateView,
    IncidentAssetLinkView,
    IncidentAssetUnlinkView,
    IncidentAssistantView,
    IncidentAssistantConfirmView,
    IncidentContactDetailView,
    IncidentContactListView,
    IncidentContactMessageListView,
    IncidentContactMessageMarkReadView,
    IncidentAttachmentConfirmView,
    IncidentAttachmentDeleteView,
    IncidentAttachmentDownloadView,
    IncidentAttachmentListView,
    IncidentBulkActionView,
    IncidentCommentListView,
    IncidentDelegateView,
    IncidentDelegationReturnView,
    IncidentDetailView,
    IncidentLinkedAlertsView,
    IncidentListView,
    IncidentTaskListView,
    IncidentTimelineView,
    IncidentTransferView,
    IncidentTransitionView,
    IncidentTriageDebugView,
    IncidentTriageView,
    PromoteView,
    StaffUserListView,
)

urlpatterns = [
    path("", IncidentListView.as_view()),
    path("bulk/", IncidentBulkActionView.as_view()),
    path("promote/", PromoteView.as_view()),
    path("staff-users/", StaffUserListView.as_view()),
    path("<str:display_id>/", IncidentDetailView.as_view()),
    path("<str:display_id>/timeline/", IncidentTimelineView.as_view()),
    path("<str:display_id>/transition/", IncidentTransitionView.as_view()),
    path("<str:display_id>/transfer/", IncidentTransferView.as_view()),
    path("<str:display_id>/delegate/", IncidentDelegateView.as_view()),
    path("<str:display_id>/delegations/<int:delegation_id>/return/", IncidentDelegationReturnView.as_view()),
    path("<str:display_id>/tasks/", IncidentTaskListView.as_view()),
    path("<str:display_id>/apply-template/", ApplyTemplateView.as_view()),
    path("<str:display_id>/comments/", IncidentCommentListView.as_view()),
    path("<str:display_id>/attachments/", IncidentAttachmentListView.as_view()),
    path("<str:display_id>/attachments/<int:attachment_id>/confirm/", IncidentAttachmentConfirmView.as_view()),
    path("<str:display_id>/attachments/<int:attachment_id>/download/", IncidentAttachmentDownloadView.as_view()),
    path("<str:display_id>/attachments/<int:attachment_id>/", IncidentAttachmentDeleteView.as_view()),
    path("<str:display_id>/assets/", IncidentAssetLinkView.as_view()),
    path("<str:display_id>/assets/<int:asset_id>/", IncidentAssetUnlinkView.as_view()),
    path("<str:display_id>/triage/", IncidentTriageView.as_view()),
    path("<str:display_id>/triage/debug/", IncidentTriageDebugView.as_view()),
    path("<str:display_id>/contacts/", IncidentContactListView.as_view()),
    path("<str:display_id>/contacts/<int:pk>/", IncidentContactDetailView.as_view()),
    path("<str:display_id>/contact-messages/", IncidentContactMessageListView.as_view()),
    path("<str:display_id>/contact-messages/mark-read/", IncidentContactMessageMarkReadView.as_view()),
    path("<str:display_id>/alerts/", IncidentLinkedAlertsView.as_view()),
    path("<str:display_id>/assistant/", IncidentAssistantView.as_view()),
    path("<str:display_id>/assistant-confirm/", IncidentAssistantConfirmView.as_view()),
]
