from django.urls import path

from .memory.views import (
    DistillationRunListView,
    LessonReviewActionView,
    LessonReviewCountView,
    LessonReviewQueueView,
)
from .views import (
    ApplyTemplateView,
    IncidentAssetLinkView,
    IncidentAssetUnlinkView,
    IncidentAssistantView,
    IncidentAssistantConfirmView,
    IncidentContactDetailView,
    IncidentContactListView,
    IncidentContactMessageListView,
    IncidentContactMessageMarkReadView,
    IncidentAttachmentConfirmView,
    IncidentAttachmentDeleteView,
    IncidentAttachmentDownloadView,
    IncidentAttachmentListView,
    IncidentAttachmentPreviewView,
    IncidentBulkActionView,
    IncidentCommentListView,
    IncidentDelegateView,
    IncidentDelegationReturnView,
    IncidentDetailView,
    IncidentIOCDetailView,
    IncidentIOCListView,
    IncidentLinkedAlertsView,
    IncidentListView,
    IncidentPresenceView,
    IncidentTaskListView,
    IncidentTimelineView,
    IncidentTrendView,
    IncidentChangeOrgView,
    IncidentTransferView,
    IncidentTransitionView,
    IncidentTriageDebugView,
    IncidentTriageView,
    IncidentReportListView,
    IncidentReportDownloadView,
    ReportListView,
    IncidentReportPreviewView,
    IncidentReportPreviewSummaryView,
    PromoteView,
    ReportSectionCatalogView,
    ReportTemplateDetailView,
    ReportTemplateListView,
    StaffUserListView,
)

urlpatterns = [
    path("", IncidentListView.as_view()),
    path("bulk/", IncidentBulkActionView.as_view()),
    path("promote/", PromoteView.as_view()),
    path("staff-users/", StaffUserListView.as_view()),
    path("trend/", IncidentTrendView.as_view()),
    path("reports/", ReportListView.as_view()),
    path("report-sections/", ReportSectionCatalogView.as_view()),
    path("report-templates/", ReportTemplateListView.as_view()),
    path("report-templates/<int:pk>/", ReportTemplateDetailView.as_view()),
    path("triage-lessons/", LessonReviewQueueView.as_view()),
    path("triage-lessons/count/", LessonReviewCountView.as_view()),
    path("triage-lessons/runs/", DistillationRunListView.as_view()),
    path("triage-lessons/<int:pk>/<str:action>/", LessonReviewActionView.as_view()),
    path("<str:display_id>/", IncidentDetailView.as_view()),
    path("<str:display_id>/timeline/", IncidentTimelineView.as_view()),
    path("<str:display_id>/transition/", IncidentTransitionView.as_view()),
    path("<str:display_id>/transfer/", IncidentTransferView.as_view()),
    path("<str:display_id>/change-org/", IncidentChangeOrgView.as_view()),
    path("<str:display_id>/delegate/", IncidentDelegateView.as_view()),
    path("<str:display_id>/delegations/<int:delegation_id>/return/", IncidentDelegationReturnView.as_view()),
    path("<str:display_id>/tasks/", IncidentTaskListView.as_view()),
    path("<str:display_id>/apply-template/", ApplyTemplateView.as_view()),
    path("<str:display_id>/comments/", IncidentCommentListView.as_view()),
    path("<str:display_id>/attachments/", IncidentAttachmentListView.as_view()),
    path("<str:display_id>/attachments/<int:attachment_id>/confirm/", IncidentAttachmentConfirmView.as_view()),
    path("<str:display_id>/attachments/<int:attachment_id>/download/", IncidentAttachmentDownloadView.as_view()),
    path("<str:display_id>/attachments/<int:attachment_id>/preview/", IncidentAttachmentPreviewView.as_view()),
    path("<str:display_id>/attachments/<int:attachment_id>/", IncidentAttachmentDeleteView.as_view()),
    path("<str:display_id>/assets/", IncidentAssetLinkView.as_view()),
    path("<str:display_id>/assets/<int:asset_id>/", IncidentAssetUnlinkView.as_view()),
    path("<str:display_id>/iocs/", IncidentIOCListView.as_view()),
    path("<str:display_id>/iocs/<int:pk>/", IncidentIOCDetailView.as_view()),
    path("<str:display_id>/reports/", IncidentReportListView.as_view()),
    path("<str:display_id>/reports/preview/", IncidentReportPreviewView.as_view()),
    path("<str:display_id>/reports/preview/summary/", IncidentReportPreviewSummaryView.as_view()),
    path("<str:display_id>/reports/<int:pk>/download/", IncidentReportDownloadView.as_view()),
    path("<str:display_id>/triage/", IncidentTriageView.as_view()),
    path("<str:display_id>/triage/debug/", IncidentTriageDebugView.as_view()),
    path("<str:display_id>/contacts/", IncidentContactListView.as_view()),
    path("<str:display_id>/contacts/<int:pk>/", IncidentContactDetailView.as_view()),
    path("<str:display_id>/contact-messages/", IncidentContactMessageListView.as_view()),
    path("<str:display_id>/contact-messages/mark-read/", IncidentContactMessageMarkReadView.as_view()),
    path("<str:display_id>/alerts/", IncidentLinkedAlertsView.as_view()),
    path("<str:display_id>/presence/", IncidentPresenceView.as_view()),
    path("<str:display_id>/assistant/", IncidentAssistantView.as_view()),
    path("<str:display_id>/assistant-confirm/", IncidentAssistantConfirmView.as_view()),
]
